---
name: Branch (main)

on:
  push:
    branches:
      - main

concurrency: ci-${{ github.ref }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-northeast-1

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      ecr_password: ${{ steps.get_password.outputs.password }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Get ECR Password
        id: get_password
        run: echo "::set-output name=password::$(aws ecr get-login-password)"

  test:
    needs: login
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: 107662415716.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
      credentials:
        username: AWS
        password: ${{ needs.login.outputs.ecr_password }}
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
        env:
          PSLOG: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo Test
        run: |
          echo "Test !!!!!!"
