---
name: build and push (to ECR)

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-northeast-1
  AWS_DEFAULT_REGION: ap-northeast-1
  ECR_REGISTRY: 107662415716.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_REPOSITORY: nginx
  IMAGE_TAG: latest

concurrency: ci-${{ github.ref }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache-docker-layers
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nginx
          IMAGE_TAG: latest
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # tags: 107662415716.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
          tags: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
