---
name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ github.head_ref }}
      - name: set PYTHON_VERSION_ASDF
        run: -|
          echo "PYTHON_VERSION_ASDF=$(grep python .tool-versions \
          cut -d ' ' -f1)" >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          # see: https://github.com/actions/python-versions/releases
          python-version: ${{ env.PYTHON_VERSION_ASDF }}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a --show-diff-on-failure
